version: "3.9"
services:
  entity-correlator:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./pyproject.toml:/app/pyproject.toml
      - ./poetry.lock:/app/poetry.lock
      - ./src:/app/src
      - ./.env:/app/.env
    tty: true
    command: ["sleep", "infinity"]
